server:
  port: 8763
eureka:
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/, http://localhost:8763/eureka/ #两个server相互注册
    register-with-eureka: true
spring:
  application:
    name: eureka-demo